### 1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

●	Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.

●	Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.

●	Исключим стоп-слова с помощью stop_words='english'.

●	Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().

In [1]:
import numpy as np
import pickle
import pandas as pd

In [51]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
with open('f_tweets.pkl', 'rb') as f:
    df = pickle.load(f)

In [4]:
df.head()

,id,label,tweet,new_tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,@user when a father is dysfunctional and is s...,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunct, selfish, drag, kid, dysfunc..."
1,2,0.0,@user @user thanks for #lyft credit i can't us...,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thank, lyft, credit, use, caus, offer, wheelc..."
2,3,0.0,bihday your majesty,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesti]"
3,4,0.0,#model i love u take with u all the time in ...,model love yoyou take with yoyou all the time ...,"[model, love, yoyou, take, with, yoyou, all, t...","[model, love, yoyou, take, yoyou, time, yoyour]","[model, love, yoyou, take, yoyou, time, yoyour]","[model, love, yoyou, take, yoyou, time, yoyour]"
4,5,0.0,factsguide: society now #motivation,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguid, societi, motiv]"

In [5]:
tweet_stemmed = df['tweet_stemmed'].apply(lambda x: ' '.join(x))

In [6]:
tweet_stemmed

0            father dysfunct selfish drag kid dysfunct run
1        thank lyft credit use caus offer wheelchair va...
2                                           bihday majesti
3                  model love yoyou take yoyou time yoyour
4                                  factsguid societi motiv
                               ...
49154    thought factori leftright polaris trump uselec...
49155    feel like mermaid hairflip neverreadi formal w...
49156    hillari campaign today ohioomg use word like a...
49157    happi work confer right mindset lead cultureof...
49158       song glad free download shoegaz newmus newsong
Name: tweet_stemmed, Length: 49159, dtype: object

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# count_vectorizer = CountVectorizer(ngram_range=(1, 2), analyzer='word', binary=False,)
count_vectorizer = CountVectorizer(stop_words='english',
                                   analyzer='word',
                                   binary=False,
                                   max_df=0.9, # игнорируем слова, частота которых в документе строго превышает порог 0.9 
                                   max_features=1000) # Ограничим количество слов, попадающий в мешок

# Создаем the Bag-of-Words модель
bag_of_words = count_vectorizer.fit_transform(tweet_stemmed)

# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
df_bag_of_words = pd.DataFrame(bag_of_words.toarray(), columns = feature_names)
# df_bag_of_words.shape
df_bag_of_words.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
tweet_lemmatized = df['tweet_lemmatized'].apply(lambda x: ' '.join(x))

bag_of_words = count_vectorizer.fit_transform(tweet_lemmatized)
feature_names = count_vectorizer.get_feature_names()
df_bag_of_words = pd.DataFrame(bag_of_words.toarray(), columns = feature_names)
df_bag_of_words.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

●	Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.

●	Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.

●	Исключим стоп-слова с помощью stop_words='english'.

●	Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(stop_words='english',
                                   max_df=0.9,
                                   max_features=1000)

values = tfidf_vectorizer.fit_transform(tweet_stemmed)

feature_names = tfidf_vectorizer.get_feature_names()
df_bag_of_words = pd.DataFrame(values.toarray(), columns = feature_names)
df_bag_of_words.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.743324,0.391965,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [12]:
values = tfidf_vectorizer.fit_transform(tweet_lemmatized)

feature_names = tfidf_vectorizer.get_feature_names()
df_bag_of_words = pd.DataFrame(values.toarray(), columns = feature_names)
df_bag_of_words.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yo,yoga,york,young,youtub,yoyou,yoyour,yoyoy,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.743324,0.391965,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

### 3. Создайте мешок слов с помощью sklearn.feature_extraction.text.HashingVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

●	Ограничим количество фичей, с помощью n_features = 1000.(можно изменить)

●	Исключим стоп-слова с помощью stop_words='english'.

In [18]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(stop_words='english',
                               n_features=1000)

values = vectorizer.fit_transform(tweet_stemmed)
print(values.shape)
print(values.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [19]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(stop_words='english',
                               n_features=1000)

values = vectorizer.fit_transform(tweet_lemmatized)
print(values.shape)
print(values.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

### 4. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [16]:
# Загружаем данные
data = open('corpus').read()
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

                                                text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [ ]:
from sklearn import model_selection, preprocessing, linear_model

train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'])

# labelEncode целевую переменную
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

## CountVectorizer

In [60]:
from sklearn.metrics import accuracy_score

count_vect = CountVectorizer(analyzer='word', 
#                              stop_words='english',
                             max_df=0.9,
#                              token_pattern=r'\w{1,}'
                            )
count_vect.fit(trainDF['text'])

xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)
# predictions

accuracy_score(valid_y, predictions)

0.8612

## TfidfVectorizer

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(stop_words='english',
                                   max_df=0.9,
#                                    max_features=100,
#                                    token_pattern=r'\w{1,}'
                                  )

tfidf_vectorizer.fit(trainDF['text'])

xtrain_hash =  tfidf_vectorizer.transform(train_x)
xvalid_hash =  tfidf_vectorizer.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_hash, train_y)
predictions = classifier.predict(xvalid_hash)
# predictions

accuracy_score(valid_y, predictions)

0.8576

## HashingVectorizer

In [61]:
from sklearn.feature_extraction.text import HashingVectorizer

vct = HashingVectorizer(analyzer='word', 
#                         token_pattern=r'\w{1,}', 
#                         n_features=1000
                       )
vct.fit(trainDF['text'])

xtrain_hash =  vct.transform(train_x)
xvalid_hash =  vct.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_hash, train_y)
predictions = classifier.predict(xvalid_hash)
# predictions

accuracy_score(valid_y, predictions)

0.834